### PR TITLE
Remove separate swift 4 style Package.swift

### PR DESCRIPTION
**Pull request by siemensikkema**

### CODE REVIEW

**Review by steffendsommer — APPROVED** [review]

**Comment by siemensikkema** [comment]
It seems the removal of the swift4 style package manifest breaks the build because it compiles in Swift 3 compatibility mode and therefore extensions can't access private fields. This means JWTKeychain wasn't actually Swift 3 compatible. Does this change our decision to keep the package manifests in swift 3 compatibility mode if it means no Swift 4 goodies? @steffendsommer

**Comment by steffendsommer** [comment]
@siemensikkema this is a bit confusing, so to get an overview and make sure we're aligned, here's my thoughts:

- Vapor 1.x projects = maintained separately in Swift 3 (not related to this)
- Vapor 2.x projects = Okay to use Swift 4.0 since most projects run Swift 4.0 and even if they were running Swift 3, we should still be able to use the package.
- Vapor 3.x projects = maintained separately (using Swift 4.1) so not related to this

I think the main thing we want to avoid is maintaining packages that are targeting Vapor 2 but using Swift 4.1, since that could include some changes that are not source compatible.

Do you agree with above?

**Comment by siemensikkema** [comment]
@steffendsommer Sounds good. So I should replace the contents of `Package.swift` with that from `Package@swift4.swift` instead?

**Comment by steffendsommer** [comment]
@siemensikkema yes sounds good to me

**Review by steffendsommer — APPROVED** [review]

**Comment by siemensikkema** [comment]
there are some Circle CI issues so I can't see what's going wrong

**Pull request merged**
